In [2]:
from gurobipy import *
import numpy as np
import pandas as pd
import sys

## Load model

In [3]:
model = read("./model/2.2.1.mps")
model.write("./model/2.2.1/model.lp")
print(f"Number of vars: {len(model.getVars())}")
print(f"Number of constraints: {len(model.getConstrs())}")
print(model.getVars())

Set parameter WLSAccessID
Set parameter WLSSecret
Set parameter LicenseID to value 2395694
Academic license 2395694 - for non-commercial use only - registered to tr___@gmail.com
Read MPS format model from file ./model/2.2.1.mps
Reading time = 0.00 seconds
2.2.1: 210 rows, 2010 columns, 4010 nonzeros
Number of vars: 2010
Number of constraints: 210
[<gurobi.Var x[0,0]>, <gurobi.Var x[0,1]>, <gurobi.Var x[0,2]>, <gurobi.Var x[0,3]>, <gurobi.Var x[0,4]>, <gurobi.Var x[0,5]>, <gurobi.Var x[0,6]>, <gurobi.Var x[0,7]>, <gurobi.Var x[0,8]>, <gurobi.Var x[0,9]>, <gurobi.Var x[0,10]>, <gurobi.Var x[0,11]>, <gurobi.Var x[0,12]>, <gurobi.Var x[0,13]>, <gurobi.Var x[0,14]>, <gurobi.Var x[0,15]>, <gurobi.Var x[0,16]>, <gurobi.Var x[0,17]>, <gurobi.Var x[0,18]>, <gurobi.Var x[0,19]>, <gurobi.Var x[0,20]>, <gurobi.Var x[0,21]>, <gurobi.Var x[0,22]>, <gurobi.Var x[0,23]>, <gurobi.Var x[0,24]>, <gurobi.Var x[0,25]>, <gurobi.Var x[0,26]>, <gurobi.Var x[0,27]>, <gurobi.Var x[0,28]>, <gurobi.Var x[0,29]>, 

## Read file

In [4]:
f = pd.read_csv("./data/2.4/Facility.csv").iloc[:, 1:].to_numpy()
f

array([[5.21e+00, 8.07e+00, 1.00e+03, 6.80e+02],
       [4.40e+00, 7.31e+00, 1.00e+03, 7.00e+02],
       [3.26e+00, 6.01e+00, 1.00e+03, 6.80e+02],
       [3.02e+00, 5.26e+00, 1.00e+03, 6.10e+02],
       [1.07e+00, 3.86e+00, 1.00e+03, 5.40e+02],
       [1.52e+00, 2.50e+00, 1.00e+03, 5.00e+02],
       [4.92e+00, 1.60e-01, 1.00e+03, 5.90e+02],
       [5.07e+00, 1.34e+00, 1.00e+03, 5.80e+02],
       [7.85e+00, 4.30e+00, 1.00e+03, 6.00e+02],
       [8.12e+00, 4.37e+00, 1.00e+03, 6.00e+02]])

In [5]:
t = pd.read_csv("./data/2.4/TransCost.csv", header=None).to_numpy()
t

array([[4.13, 5.83, 6.18, ..., 2.21, 2.45, 3.52],
       [3.15, 4.78, 5.17, ..., 2.22, 2.1 , 3.13],
       [1.78, 3.14, 3.64, ..., 3.02, 2.47, 3.11],
       ...,
       [3.26, 3.25, 2.55, ..., 4.94, 4.38, 3.46],
       [4.23, 5.7 , 5.43, ..., 2.41, 2.54, 1.83],
       [4.51, 5.98, 5.71, ..., 2.55, 2.74, 2.08]])

In [6]:
D = pd.read_csv("./data/2.4/DemandMinus.csv").iloc[:, 1:].to_numpy()
D

array([[ 3.616,  4.262, 21.   ],
       [ 2.29 ,  3.025, 25.   ],
       [ 2.757,  2.403, 29.   ],
       [ 2.882,  3.153, 29.   ],
       [ 3.552,  3.725, 24.   ],
       [ 3.623,  4.158, 18.   ],
       [ 2.94 ,  4.729, 13.   ],
       [ 2.377,  4.115, 39.   ],
       [ 3.617,  3.784, 16.   ],
       [ 2.736,  2.716, 10.   ],
       [ 4.836,  4.996,  6.   ],
       [ 3.287,  4.179, 37.   ],
       [ 5.077,  4.778,  8.   ],
       [ 2.56 ,  2.246, 16.   ],
       [ 2.83 ,  4.729,  6.   ],
       [ 2.603,  3.376, 10.   ],
       [ 5.336,  3.708, 17.   ],
       [ 4.49 ,  3.064, 37.   ],
       [ 4.473,  4.6  , 14.   ],
       [ 2.348,  4.35 , 37.   ],
       [ 5.435,  4.345,  4.   ],
       [ 3.182,  4.466, 13.   ],
       [ 2.618,  3.456, 13.   ],
       [ 5.179,  2.999, 28.   ],
       [ 3.205,  2.515, 37.   ],
       [ 2.352,  4.139, 15.   ],
       [ 2.963,  2.916, 17.   ],
       [ 3.853,  2.288, 11.   ],
       [ 4.116,  2.564, 33.   ],
       [ 4.164,  4.201, 24.   ],
       [ 2

## Read vars

In [7]:
x = {}
c = {}

for i in range(10):
    c[i] = model.getVarByName(f"chose[{i}]")
    for j in range(200):
        x[i, j] = model.getVarByName(f"x[{i},{j}]")

c

{0: <gurobi.Var chose[0]>,
 1: <gurobi.Var chose[1]>,
 2: <gurobi.Var chose[2]>,
 3: <gurobi.Var chose[3]>,
 4: <gurobi.Var chose[4]>,
 5: <gurobi.Var chose[5]>,
 6: <gurobi.Var chose[6]>,
 7: <gurobi.Var chose[7]>,
 8: <gurobi.Var chose[8]>,
 9: <gurobi.Var chose[9]>}

## Calculate 2.4

Calculate 2.2.1

In [8]:
model.optimize()

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (win64 - Windows 11.0 (22631.2))

CPU model: AMD Ryzen 7 5800H with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Academic license 2395694 - for non-commercial use only - registered to tr___@gmail.com
Optimize a model with 210 rows, 2010 columns and 4010 nonzeros
Model fingerprint: 0x601840fa
Variable types: 0 continuous, 2010 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [3e-01, 7e+02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [7e+00, 4e+01]
Found heuristic solution: objective 23918.380000
Presolve time: 0.01s
Presolved: 210 rows, 2010 columns, 4010 nonzeros
Variable types: 0 continuous, 2010 integer (10 binary)
Found heuristic solution: objective 23657.160000

Root relaxation: objective 1.093869e+04, 239 iterations, 0.00 seconds (0.00 work units)

    Nodes    |    Current Node    |     Objecti

Update the demand

In [9]:
# if model.status == GRB.Status.OPTIMAL:
for i in range(10):
    if not c[i].X:
        model.addConstr(c[i] == 0)
for j in range(200):
    temp = model.getConstrByName(f"shop-demand[{j}]")
    if temp: model.remove(temp)
    model.addConstr(quicksum(x[i, j] for i in range(10)) >= D[j, -1])

model.write("./model/2.4/model.lp")
model.optimize()

Gurobi Optimizer version 11.0.2 build v11.0.2rc0 (win64 - Windows 11.0 (22631.2))

CPU model: AMD Ryzen 7 5800H with Radeon Graphics, instruction set [SSE2|AVX|AVX2]
Thread count: 8 physical cores, 16 logical processors, using up to 16 threads

Academic license 2395694 - for non-commercial use only - registered to tr___@gmail.com
Optimize a model with 215 rows, 2010 columns and 4015 nonzeros
Model fingerprint: 0x4efd2fab
Variable types: 0 continuous, 2010 integer (10 binary)
Coefficient statistics:
  Matrix range     [1e+00, 1e+03]
  Objective range  [3e-01, 7e+02]
  Bounds range     [1e+00, 1e+00]
  RHS range        [4e+00, 4e+01]

Loaded MIP start from previous solve with objective 11326.8

Presolve removed 10 rows and 1005 columns
Presolve time: 0.01s
Presolved: 205 rows, 1005 columns, 2005 nonzeros
Found heuristic solution: objective 9620.6900000
Variable types: 0 continuous, 1005 integer (5 binary)
Found heuristic solution: objective 9602.9300000

Root relaxation: objective 8.7121

Solve the model again

In [11]:
if model.status == GRB.Status.OPTIMAL:
    temp = sys.stdout
    sys.stdout = open("./out/2.4.out", "w")
    # print(0, end=" ")
    for i in range(10):
        print(round(c[i].X), end=" ")
    print()
    for i in range(10):
        if c[i].X:
            for j in range(200):
                if x[i, j].X != 0:
                    print(f"{i + 1} {j + 1} {x[i, j].X}")
    print(model.ObjVal)
    sys.stdout = temp